// <auto-generated />
using System;
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(BackendContext))]
    [Migration("20221124181831_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EntityLayer.Concrete.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMissing")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Species")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Pets");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Pet");
                });

            modelBuilder.Entity("EntityLayer.Concrete.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PetsFound")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "78034 Jonatan Ville, Port Jedidiah, United States of America",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(4696),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(4710),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Jaylin",
                            Password = "fvn3pS2GQiv6PJg",
                            PetsFound = 0,
                            PhoneNumber = "1-616-530-1220",
                            Surname = "Nikolaus",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(4709),
                            UpdatedBy = 0,
                            Username = "Nelson_Collins"
                        },
                        new
                        {
                            Id = 2,
                            Address = "3704 Pollich Inlet, Rempelshire, Hong Kong",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(6079),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(6081),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Ava",
                            Password = "mBIT2SurVGtpEHj",
                            PetsFound = 0,
                            PhoneNumber = "537-213-7868",
                            Surname = "Harber",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(6081),
                            UpdatedBy = 0,
                            Username = "Maureen.Mayer27"
                        },
                        new
                        {
                            Id = 3,
                            Address = "050 Cathryn Station, West Jordon, Andorra",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(6375),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(6377),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Rudy",
                            Password = "JTuk37UOkZoRYmD",
                            PetsFound = 0,
                            PhoneNumber = "(771) 382-6802 x218",
                            Surname = "Connelly",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(6376),
                            UpdatedBy = 0,
                            Username = "Suzanne39"
                        },
                        new
                        {
                            Id = 4,
                            Address = "7235 Antonina Port, Macejkovicfort, Morocco",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(6625),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(6627),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Hilbert",
                            Password = "rnHUc8_w4vNJd7a",
                            PetsFound = 0,
                            PhoneNumber = "757-979-2883 x239",
                            Surname = "MacGyver",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(6626),
                            UpdatedBy = 0,
                            Username = "Vidal72"
                        },
                        new
                        {
                            Id = 5,
                            Address = "75546 Monahan Wells, O'Connellfurt, Hong Kong",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(6862),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(6863),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Marcia",
                            Password = "j_C40eT7RSiKdQc",
                            PetsFound = 0,
                            PhoneNumber = "935-330-0318 x501",
                            Surname = "Rolfson",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(6862),
                            UpdatedBy = 0,
                            Username = "Alberta.Green"
                        },
                        new
                        {
                            Id = 6,
                            Address = "6560 Floyd Vista, New Jamaal, Cook Islands",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(7174),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(7176),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Marian",
                            Password = "Wi3p8SMLkMG5ue0",
                            PetsFound = 0,
                            PhoneNumber = "(401) 215-2652 x3151",
                            Surname = "Christiansen",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(7176),
                            UpdatedBy = 0,
                            Username = "Ashton.Donnelly27"
                        },
                        new
                        {
                            Id = 7,
                            Address = "375 Waldo Camp, North Juvenal, Morocco",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(7478),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(7480),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Kailey",
                            Password = "q3ufJjWnS917ryY",
                            PetsFound = 0,
                            PhoneNumber = "646.500.2768 x0120",
                            Surname = "Koepp",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(7480),
                            UpdatedBy = 0,
                            Username = "Geo_Bins64"
                        },
                        new
                        {
                            Id = 8,
                            Address = "07578 Alisa Avenue, McCulloughport, Norfolk Island",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(7748),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(7749),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Soledad",
                            Password = "0P_Xz0uaTrYxyff",
                            PetsFound = 0,
                            PhoneNumber = "(972) 344-7348 x2100",
                            Surname = "Hamill",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(7749),
                            UpdatedBy = 0,
                            Username = "Ford_Heaney70"
                        },
                        new
                        {
                            Id = 9,
                            Address = "41618 Lesch Plaza, Titusview, Bulgaria",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(8024),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(8026),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Johnpaul",
                            Password = "1_ssSrRJKSUELUC",
                            PetsFound = 0,
                            PhoneNumber = "800-498-2319 x62954",
                            Surname = "Champlin",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(8025),
                            UpdatedBy = 0,
                            Username = "Isaias_MacGyver19"
                        },
                        new
                        {
                            Id = 10,
                            Address = "546 Annabelle Oval, Christiansenstad, French Southern Territories",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(8309),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(8311),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Baylee",
                            Password = "mphZWSC21XN5gDk",
                            PetsFound = 0,
                            PhoneNumber = "865.279.1781",
                            Surname = "Stark",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(8310),
                            UpdatedBy = 0,
                            Username = "Benjamin_Dicki33"
                        },
                        new
                        {
                            Id = 11,
                            Address = "711 Welch Springs, Bednarport, Kiribati",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(8574),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(8575),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Wilfredo",
                            Password = "XKvh5hndWfcNIKo",
                            PetsFound = 0,
                            PhoneNumber = "(958) 771-6271 x38870",
                            Surname = "Wolff",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(8575),
                            UpdatedBy = 0,
                            Username = "Sterling_MacGyver45"
                        },
                        new
                        {
                            Id = 12,
                            Address = "997 Gayle Springs, Port Ned, Belarus",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(8860),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(8861),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Lon",
                            Password = "9PCXPB_0j9cqs2b",
                            PetsFound = 0,
                            PhoneNumber = "567.457.2491 x8339",
                            Surname = "Goyette",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(8860),
                            UpdatedBy = 0,
                            Username = "Jackeline_Conroy61"
                        },
                        new
                        {
                            Id = 13,
                            Address = "671 Borer Garden, Sigurdborough, Hong Kong",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(9129),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(9131),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Kiera",
                            Password = "XYGowscUa0vpqtm",
                            PetsFound = 0,
                            PhoneNumber = "535.520.4487",
                            Surname = "McLaughlin",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(9130),
                            UpdatedBy = 0,
                            Username = "Jonas63"
                        },
                        new
                        {
                            Id = 14,
                            Address = "7308 Spinka Forge, Irmaburgh, Andorra",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(9390),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(9392),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Darwin",
                            Password = "ARX8JvnKaKSuJ3u",
                            PetsFound = 0,
                            PhoneNumber = "921.898.5626",
                            Surname = "Barrows",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(9392),
                            UpdatedBy = 0,
                            Username = "Garth14"
                        },
                        new
                        {
                            Id = 15,
                            Address = "106 Joey Camp, Arvidbury, Grenada",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(9657),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(9658),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Ruben",
                            Password = "AjEyuoH63Gshnyw",
                            PetsFound = 0,
                            PhoneNumber = "(769) 701-9961 x96072",
                            Surname = "Cummings",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(9657),
                            UpdatedBy = 0,
                            Username = "Jaquan_Kemmer"
                        },
                        new
                        {
                            Id = 16,
                            Address = "6479 Pollich Glen, South Leannamouth, Virgin Islands, British",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(9915),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(9916),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Gerda",
                            Password = "oMfxHYKUlQDP04F",
                            PetsFound = 0,
                            PhoneNumber = "1-393-223-3129",
                            Surname = "Sipes",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 908, DateTimeKind.Local).AddTicks(9916),
                            UpdatedBy = 0,
                            Username = "Buddy76"
                        },
                        new
                        {
                            Id = 17,
                            Address = "158 Frances Springs, New Ahmed, Ethiopia",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(182),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(183),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Kaylin",
                            Password = "kIHUfQVTAJsZksF",
                            PetsFound = 0,
                            PhoneNumber = "1-779-425-9049 x149",
                            Surname = "Wisozk",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(183),
                            UpdatedBy = 0,
                            Username = "Harvey_Kertzmann30"
                        },
                        new
                        {
                            Id = 18,
                            Address = "526 Michael Ridge, North Mariehaven, Northern Mariana Islands",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(462),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(463),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Aleen",
                            Password = "5Al7UGNvarXr16h",
                            PetsFound = 0,
                            PhoneNumber = "568.976.0946 x171",
                            Surname = "Nikolaus",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(463),
                            UpdatedBy = 0,
                            Username = "Kathryn.Padberg56"
                        },
                        new
                        {
                            Id = 19,
                            Address = "646 Runolfsdottir Vista, Sydneyland, Mayotte",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(742),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(744),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Rebeca",
                            Password = "hVa3rV66FwJOe_h",
                            PetsFound = 0,
                            PhoneNumber = "1-959-822-5919",
                            Surname = "Wiza",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(743),
                            UpdatedBy = 0,
                            Username = "Devyn_Hermann"
                        },
                        new
                        {
                            Id = 20,
                            Address = "9333 Stiedemann Centers, Port Esteban, United States Minor Outlying Islands",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(1013),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(1014),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Thea",
                            Password = "DiRqAa8z0j0Iy5W",
                            PetsFound = 0,
                            PhoneNumber = "203-735-2749",
                            Surname = "Emmerich",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(1014),
                            UpdatedBy = 0,
                            Username = "Eva.Kunde"
                        },
                        new
                        {
                            Id = 21,
                            Address = "78843 Eldred Mountain, South Teresafort, Iraq",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(1276),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(1277),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Magnus",
                            Password = "PYHLcN7vfiOF3mp",
                            PetsFound = 0,
                            PhoneNumber = "(428) 441-2895 x1138",
                            Surname = "Veum",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(1277),
                            UpdatedBy = 0,
                            Username = "Adalberto.Christiansen"
                        },
                        new
                        {
                            Id = 22,
                            Address = "011 Anjali Islands, Port Conormouth, Democratic People's Republic of Korea",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(1595),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(1596),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Christop",
                            Password = "ryh3t6ZhqAYc8y8",
                            PetsFound = 0,
                            PhoneNumber = "(972) 212-4717 x63525",
                            Surname = "Casper",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(1596),
                            UpdatedBy = 0,
                            Username = "Meda65"
                        },
                        new
                        {
                            Id = 23,
                            Address = "3322 White Prairie, Quincyfurt, Cote d'Ivoire",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(1889),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(1890),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Corene",
                            Password = "8YVsmMofqDII5l3",
                            PetsFound = 0,
                            PhoneNumber = "(697) 727-6305 x630",
                            Surname = "Hermann",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(1890),
                            UpdatedBy = 0,
                            Username = "Kendall91"
                        },
                        new
                        {
                            Id = 24,
                            Address = "8529 Annalise Alley, Tristonfurt, Isle of Man",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(2162),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(2163),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Jennifer",
                            Password = "wQkcJhBOx8LiGWj",
                            PetsFound = 0,
                            PhoneNumber = "1-899-316-0364",
                            Surname = "Monahan",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(2162),
                            UpdatedBy = 0,
                            Username = "Helga14"
                        },
                        new
                        {
                            Id = 25,
                            Address = "59913 Helmer Lake, South Clementine, Saint Helena",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(2414),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(2415),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Herta",
                            Password = "RAMbWZo3dD_ZziD",
                            PetsFound = 0,
                            PhoneNumber = "1-526-677-6567",
                            Surname = "Hickle",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(2414),
                            UpdatedBy = 0,
                            Username = "Lavonne71"
                        },
                        new
                        {
                            Id = 26,
                            Address = "38404 Moriah Rest, Schultzfort, Svalbard & Jan Mayen Islands",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(2695),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(2697),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Afton",
                            Password = "zu7BRVsMpE2ExrA",
                            PetsFound = 0,
                            PhoneNumber = "1-699-898-4089 x2596",
                            Surname = "Fritsch",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(2696),
                            UpdatedBy = 0,
                            Username = "Syble.Glover"
                        },
                        new
                        {
                            Id = 27,
                            Address = "48654 Smith Radial, Lake Carmel, Malta",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(2960),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(2961),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Robb",
                            Password = "VRoKP9g4HqbiFS7",
                            PetsFound = 0,
                            PhoneNumber = "501-583-2066",
                            Surname = "Kirlin",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(2961),
                            UpdatedBy = 0,
                            Username = "Mariah7"
                        },
                        new
                        {
                            Id = 28,
                            Address = "66199 Ken Ports, East Reyton, Jamaica",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(3223),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(3225),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Carmela",
                            Password = "EhB496e1EYwH8la",
                            PetsFound = 0,
                            PhoneNumber = "(392) 614-5267 x309",
                            Surname = "Heidenreich",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(3224),
                            UpdatedBy = 0,
                            Username = "Federico_Krajcik85"
                        },
                        new
                        {
                            Id = 29,
                            Address = "1039 Bethany Plaza, West Erling, Fiji",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(3505),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(3506),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Amara",
                            Password = "Ff4NFPj_KZ_RMjy",
                            PetsFound = 0,
                            PhoneNumber = "1-361-598-8909 x30602",
                            Surname = "O'Conner",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(3506),
                            UpdatedBy = 0,
                            Username = "Karley67"
                        },
                        new
                        {
                            Id = 30,
                            Address = "474 Jeffery Station, Stromanmouth, Montserrat",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(3767),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(3769),
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Jedediah",
                            Password = "n1xlap1fuDOFsS7",
                            PetsFound = 0,
                            PhoneNumber = "205.212.4218 x75455",
                            Surname = "Thiel",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(3768),
                            UpdatedBy = 0,
                            Username = "Barney55"
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.FoundPet", b =>
                {
                    b.HasBaseType("EntityLayer.Concrete.Pet");

                    b.Property<DateTime>("FindingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FoundAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasDiscriminator().HasValue("FoundPet");

                    b.HasData(
                        new
                        {
                            Id = 16,
                            Age = 5,
                            Breed = "English setter",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(7337),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(7338),
                            DeletedBy = 0,
                            Health = "Sağlıklı",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Enos",
                            Species = "Dog",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(7338),
                            UpdatedBy = 0,
                            UserId = 25,
                            FindingDate = new DateTime(2022, 9, 11, 6, 51, 1, 56, DateTimeKind.Local).AddTicks(8132),
                            FoundAddress = "13774 Arnaldo Knolls, East Peterside, Macao"
                        },
                        new
                        {
                            Id = 17,
                            Age = 26,
                            Breed = "Jenday Conure",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(8026),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(8027),
                            DeletedBy = 0,
                            Health = "Kanaması var",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Bobby",
                            Species = "Bird",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(8026),
                            UpdatedBy = 0,
                            UserId = 9,
                            FindingDate = new DateTime(2021, 12, 14, 12, 53, 51, 701, DateTimeKind.Local).AddTicks(821),
                            FoundAddress = "3020 Hilll Camp, North Royce, Bahrain"
                        },
                        new
                        {
                            Id = 18,
                            Age = 26,
                            Breed = "Abyssinian",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(8210),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(8211),
                            DeletedBy = 0,
                            Health = "Sağlıklı",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Aida",
                            Species = "Cat",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(8211),
                            UpdatedBy = 0,
                            UserId = 19,
                            FindingDate = new DateTime(2022, 5, 29, 10, 15, 33, 361, DateTimeKind.Local).AddTicks(2249),
                            FoundAddress = "63304 Seamus Lake, Funkstad, Bangladesh"
                        },
                        new
                        {
                            Id = 19,
                            Age = 17,
                            Breed = "Brussels griffon",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(8372),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(8373),
                            DeletedBy = 0,
                            Health = "Yaralı",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Brooke",
                            Species = "Dog",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(8372),
                            UpdatedBy = 0,
                            UserId = 5,
                            FindingDate = new DateTime(2022, 1, 31, 1, 45, 16, 269, DateTimeKind.Local).AddTicks(5231),
                            FoundAddress = "985 Antoinette Drives, Lake Hardyland, Belgium"
                        },
                        new
                        {
                            Id = 20,
                            Age = 27,
                            Breed = "Canary",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(8547),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(8548),
                            DeletedBy = 0,
                            Health = "Yaralı",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Shemar",
                            Species = "Bird",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(8548),
                            UpdatedBy = 0,
                            UserId = 18,
                            FindingDate = new DateTime(2022, 1, 15, 23, 28, 58, 625, DateTimeKind.Local).AddTicks(5518),
                            FoundAddress = "88777 Patricia Center, Skylaview, Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 21,
                            Age = 6,
                            Breed = "Maine Coon",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(8708),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(8709),
                            DeletedBy = 0,
                            Health = "Halsiz",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Aracely",
                            Species = "Cat",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(8708),
                            UpdatedBy = 0,
                            UserId = 2,
                            FindingDate = new DateTime(2022, 8, 22, 9, 26, 50, 763, DateTimeKind.Local).AddTicks(9545),
                            FoundAddress = "470 Hyatt Cliff, Efrainborough, Christmas Island"
                        },
                        new
                        {
                            Id = 22,
                            Age = 11,
                            Breed = "Clumber spaniel",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(8867),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(8868),
                            DeletedBy = 0,
                            Health = "Hasta",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Ebony",
                            Species = "Dog",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(8868),
                            UpdatedBy = 0,
                            UserId = 19,
                            FindingDate = new DateTime(2022, 1, 4, 16, 0, 12, 607, DateTimeKind.Local).AddTicks(9923),
                            FoundAddress = "90151 Queen Unions, Myrtleburgh, Niue"
                        },
                        new
                        {
                            Id = 23,
                            Age = 16,
                            Breed = "Crimson Rosella",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(9057),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(9058),
                            DeletedBy = 0,
                            Health = "Hasta",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Dorthy",
                            Species = "Bird",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(9057),
                            UpdatedBy = 0,
                            UserId = 15,
                            FindingDate = new DateTime(2022, 7, 25, 10, 8, 49, 361, DateTimeKind.Local).AddTicks(2038),
                            FoundAddress = "226 Maybell Parks, East Laverne, Sierra Leone"
                        },
                        new
                        {
                            Id = 24,
                            Age = 12,
                            Breed = "Himalayan",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(9219),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(9220),
                            DeletedBy = 0,
                            Health = "Hasta",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Raquel",
                            Species = "Cat",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(9220),
                            UpdatedBy = 0,
                            UserId = 27,
                            FindingDate = new DateTime(2022, 10, 25, 15, 13, 33, 227, DateTimeKind.Local).AddTicks(612),
                            FoundAddress = "7089 Jerry Streets, East Jaidaport, Malta"
                        },
                        new
                        {
                            Id = 25,
                            Age = 16,
                            Breed = "pointer",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(9391),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(9392),
                            DeletedBy = 0,
                            Health = "Yaralı",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Greyson",
                            Species = "Dog",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(9391),
                            UpdatedBy = 0,
                            UserId = 17,
                            FindingDate = new DateTime(2022, 6, 4, 17, 55, 19, 598, DateTimeKind.Local).AddTicks(8671),
                            FoundAddress = "0371 Hartmann Mills, New Caseymouth, Eritrea"
                        },
                        new
                        {
                            Id = 26,
                            Age = 2,
                            Breed = "green-cheeked conure",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(9558),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(9559),
                            DeletedBy = 0,
                            Health = "Hasta",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Althea",
                            Species = "Bird",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(9559),
                            UpdatedBy = 0,
                            UserId = 3,
                            FindingDate = new DateTime(2022, 10, 13, 7, 59, 5, 803, DateTimeKind.Local).AddTicks(2738),
                            FoundAddress = "730 Denesik Branch, Alanisberg, Heard Island and McDonald Islands"
                        },
                        new
                        {
                            Id = 27,
                            Age = 20,
                            Breed = "Russian Blue",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(9719),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(9720),
                            DeletedBy = 0,
                            Health = "Kanaması var",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Lilian",
                            Species = "Cat",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(9719),
                            UpdatedBy = 0,
                            UserId = 12,
                            FindingDate = new DateTime(2022, 2, 5, 12, 59, 47, 603, DateTimeKind.Local).AddTicks(57),
                            FoundAddress = "5078 Wilfredo Keys, Andersonshire, Brunei Darussalam"
                        },
                        new
                        {
                            Id = 28,
                            Age = 4,
                            Breed = "Rottweiler",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(9897),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(9898),
                            DeletedBy = 0,
                            Health = "Sağlıklı",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Edwina",
                            Species = "Dog",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(9898),
                            UpdatedBy = 0,
                            UserId = 10,
                            FindingDate = new DateTime(2022, 8, 21, 6, 6, 8, 971, DateTimeKind.Local).AddTicks(2643),
                            FoundAddress = "67244 Gerson Garden, North Vernice, Haiti"
                        },
                        new
                        {
                            Id = 29,
                            Age = 1,
                            Breed = "Rainbow Lory",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 910, DateTimeKind.Local).AddTicks(58),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 910, DateTimeKind.Local).AddTicks(59),
                            DeletedBy = 0,
                            Health = "Hasta",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Avis",
                            Species = "Bird",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 910, DateTimeKind.Local).AddTicks(58),
                            UpdatedBy = 0,
                            UserId = 21,
                            FindingDate = new DateTime(2022, 6, 18, 0, 12, 34, 127, DateTimeKind.Local).AddTicks(5185),
                            FoundAddress = "93534 Freeman Corners, East Carlo, Cape Verde"
                        },
                        new
                        {
                            Id = 30,
                            Age = 13,
                            Breed = "Manx",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 910, DateTimeKind.Local).AddTicks(219),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 910, DateTimeKind.Local).AddTicks(220),
                            DeletedBy = 0,
                            Health = "Kanaması var",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Kieran",
                            Species = "Cat",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 910, DateTimeKind.Local).AddTicks(220),
                            UpdatedBy = 0,
                            UserId = 23,
                            FindingDate = new DateTime(2021, 12, 11, 12, 21, 34, 49, DateTimeKind.Local).AddTicks(5088),
                            FoundAddress = "603 Gleichner Ferry, North Jarretstad, United States Minor Outlying Islands"
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.MissingPet", b =>
                {
                    b.HasBaseType("EntityLayer.Concrete.Pet");

                    b.Property<string>("LastSeenAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("MissingDate")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("MissingPet");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 12,
                            Breed = "Kerry blue terrier",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(4133),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(4134),
                            DeletedBy = 0,
                            Health = "Kanaması var",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Jeremie",
                            Species = "Dog",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(4133),
                            UpdatedBy = 0,
                            UserId = 26,
                            LastSeenAddress = "511 Madyson Street, East Kasey, Georgia",
                            MissingDate = new DateTime(2022, 3, 2, 11, 17, 40, 894, DateTimeKind.Local).AddTicks(4991)
                        },
                        new
                        {
                            Id = 2,
                            Age = 12,
                            Breed = "Rainbow Lory",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(4898),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(4899),
                            DeletedBy = 0,
                            Health = "Kanaması var",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Alexandre",
                            Species = "Bird",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(4899),
                            UpdatedBy = 0,
                            UserId = 28,
                            LastSeenAddress = "824 Becker Highway, Wisozkton, Dominica",
                            MissingDate = new DateTime(2022, 6, 6, 3, 59, 50, 84, DateTimeKind.Local).AddTicks(2978)
                        },
                        new
                        {
                            Id = 3,
                            Age = 25,
                            Breed = "Abyssinian Cat",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(5085),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(5086),
                            DeletedBy = 0,
                            Health = "Hasta",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Ryan",
                            Species = "Cat",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(5086),
                            UpdatedBy = 0,
                            UserId = 29,
                            LastSeenAddress = "09410 Issac Plaza, New Antonioport, Togo",
                            MissingDate = new DateTime(2022, 3, 21, 16, 26, 12, 982, DateTimeKind.Local).AddTicks(3938)
                        },
                        new
                        {
                            Id = 4,
                            Age = 9,
                            Breed = "schnauzer",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(5267),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(5268),
                            DeletedBy = 0,
                            Health = "Yaralı",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Derick",
                            Species = "Dog",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(5267),
                            UpdatedBy = 0,
                            UserId = 19,
                            LastSeenAddress = "877 Mia Divide, Francescaville, Chile",
                            MissingDate = new DateTime(2022, 6, 2, 13, 22, 10, 500, DateTimeKind.Local).AddTicks(4680)
                        },
                        new
                        {
                            Id = 5,
                            Age = 2,
                            Breed = "Quaker Parakeet",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(5457),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(5458),
                            DeletedBy = 0,
                            Health = "Sağlıklı",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Jo",
                            Species = "Bird",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(5457),
                            UpdatedBy = 0,
                            UserId = 26,
                            LastSeenAddress = "085 Jesus Mill, Desireestad, Panama",
                            MissingDate = new DateTime(2022, 8, 14, 13, 8, 46, 91, DateTimeKind.Local).AddTicks(1227)
                        },
                        new
                        {
                            Id = 6,
                            Age = 25,
                            Breed = "Turkish Angora",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(5620),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(5621),
                            DeletedBy = 0,
                            Health = "Yaralı",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Maribel",
                            Species = "Cat",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(5621),
                            UpdatedBy = 0,
                            UserId = 16,
                            LastSeenAddress = "905 Osinski Landing, Annettaville, Maldives",
                            MissingDate = new DateTime(2022, 8, 3, 1, 11, 8, 37, DateTimeKind.Local).AddTicks(2271)
                        },
                        new
                        {
                            Id = 7,
                            Age = 21,
                            Breed = "poodle",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(5786),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(5787),
                            DeletedBy = 0,
                            Health = "Sağlıklı",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Holly",
                            Species = "Dog",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(5787),
                            UpdatedBy = 0,
                            UserId = 7,
                            LastSeenAddress = "2728 Rudy Wells, South Earlinetown, Burkina Faso",
                            MissingDate = new DateTime(2022, 6, 28, 14, 37, 2, 166, DateTimeKind.Local).AddTicks(1411)
                        },
                        new
                        {
                            Id = 8,
                            Age = 18,
                            Breed = "Blue-Crowned Conure",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(5958),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(5959),
                            DeletedBy = 0,
                            Health = "Kanaması var",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Terrance",
                            Species = "Bird",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(5958),
                            UpdatedBy = 0,
                            UserId = 6,
                            LastSeenAddress = "2226 Russel Square, Auerfurt, Spain",
                            MissingDate = new DateTime(2022, 3, 14, 23, 2, 35, 36, DateTimeKind.Local).AddTicks(3026)
                        },
                        new
                        {
                            Id = 9,
                            Age = 1,
                            Breed = "British Shorthair",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(6108),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(6109),
                            DeletedBy = 0,
                            Health = "Kanaması var",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Mireille",
                            Species = "Cat",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(6109),
                            UpdatedBy = 0,
                            UserId = 24,
                            LastSeenAddress = "713 Jalon Haven, Amaniport, Palau",
                            MissingDate = new DateTime(2022, 9, 28, 15, 8, 50, 963, DateTimeKind.Local).AddTicks(1803)
                        },
                        new
                        {
                            Id = 10,
                            Age = 18,
                            Breed = "Skye terrier",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(6264),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(6265),
                            DeletedBy = 0,
                            Health = "Sağlıklı",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Issac",
                            Species = "Dog",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(6265),
                            UpdatedBy = 0,
                            UserId = 23,
                            LastSeenAddress = "255 Ziemann Green, Port Lenny, Paraguay",
                            MissingDate = new DateTime(2022, 7, 28, 6, 16, 58, 871, DateTimeKind.Local).AddTicks(9092)
                        },
                        new
                        {
                            Id = 11,
                            Age = 0,
                            Breed = "Psittacula",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(6420),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(6421),
                            DeletedBy = 0,
                            Health = "Yaralı",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Fern",
                            Species = "Bird",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(6421),
                            UpdatedBy = 0,
                            UserId = 29,
                            LastSeenAddress = "956 Garnet Squares, Shayneborough, Liechtenstein",
                            MissingDate = new DateTime(2022, 7, 10, 8, 44, 23, 321, DateTimeKind.Local).AddTicks(8019)
                        },
                        new
                        {
                            Id = 12,
                            Age = 17,
                            Breed = "Persian",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(6579),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(6580),
                            DeletedBy = 0,
                            Health = "Kanaması var",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Janelle",
                            Species = "Cat",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(6580),
                            UpdatedBy = 0,
                            UserId = 10,
                            LastSeenAddress = "63074 Orie Roads, Ulisesport, Greenland",
                            MissingDate = new DateTime(2022, 3, 10, 11, 48, 11, 669, DateTimeKind.Local).AddTicks(9125)
                        },
                        new
                        {
                            Id = 13,
                            Age = 18,
                            Breed = "bichon frise",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(6741),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(6741),
                            DeletedBy = 0,
                            Health = "Hasta",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Edna",
                            Species = "Dog",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(6741),
                            UpdatedBy = 0,
                            UserId = 10,
                            LastSeenAddress = "22345 Greenholt Lodge, South Elyse, Cook Islands",
                            MissingDate = new DateTime(2022, 5, 18, 9, 32, 44, 383, DateTimeKind.Local).AddTicks(4019)
                        },
                        new
                        {
                            Id = 14,
                            Age = 29,
                            Breed = "green-winged macaw",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(6894),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(6895),
                            DeletedBy = 0,
                            Health = "Hasta",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Andres",
                            Species = "Bird",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(6894),
                            UpdatedBy = 0,
                            UserId = 10,
                            LastSeenAddress = "6655 Harrison Islands, Grahamton, Holy See (Vatican City State)",
                            MissingDate = new DateTime(2022, 11, 18, 16, 53, 29, 132, DateTimeKind.Local).AddTicks(3597)
                        },
                        new
                        {
                            Id = 15,
                            Age = 27,
                            Breed = "Burmese",
                            CreatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(7107),
                            CreatedBy = 0,
                            DeletedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(7108),
                            DeletedBy = 0,
                            Health = "Kanaması var",
                            IsDeleted = false,
                            IsMissing = false,
                            Name = "Christ",
                            Species = "Cat",
                            UpdatedAt = new DateTime(2022, 11, 24, 21, 18, 30, 909, DateTimeKind.Local).AddTicks(7107),
                            UpdatedBy = 0,
                            UserId = 1,
                            LastSeenAddress = "21969 Kemmer Square, Jadynside, Bangladesh",
                            MissingDate = new DateTime(2022, 5, 2, 9, 23, 53, 634, DateTimeKind.Local).AddTicks(6505)
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.Pet", b =>
                {
                    b.HasOne("EntityLayer.Concrete.User", "User")
                        .WithMany("Pets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EntityLayer.Concrete.User", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
